CREATE TABLE dbo.Organism
(
	Id BIGINT NOT NULL PRIMARY KEY IDENTITY,
    CurrentStateId BIGINT NOT NULL,
    Red DECIMAL(2, 2) NOT NULL,
    Green DECIMAL(2, 2) NOT NULL,
    Blue DECIMAL(2, 2) NOT NULL,
)
